services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - PORT=${PORT}
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database

  database:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"