export * from "./cnpj-already-in-use";
export * from "./phone-already-in-use";
export * from "./email-already-in-use";
export * from "./student-already-created";
export * from "./user-to-be-student-not-exists";
export * from "./course-not-exists";
export * from "./professor-already-created";
export * from "./user-to-be-professor-not-exists";
export * from "./course-name-already-in-use";
export * from "./discipline-name-already-in-use";
export * from "./institution-already-have-manager";
export * from "./institution-not-exists";
export * from "./session";
export * from "./auth-manager";
export * as AuthUser from "./auth-user";
export * from "./unexpected";
export * from "./user-to-be-student-is-manager";
export * from "./user-to-be-professor-is-manager";
